apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: i4a8dxl2v-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: i4a8dxl2v-python 
  name: i4a8dxl2v-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: i4a8dxl2v-python 
